### ISSUE TITLE
PAA doesn't behave as expected for series whose length is not multiple of paa size

### ISSUE THREAD

**Issue by GabrieleCocco** [jMotif/SAX#10]
I was starting from your code to create a SAX processor that operates reactively.
While coding PAA to operates on enumerables/observable collections I found something that I guess it's an error in [TSProcessor PAA implementation](https://github.com/jMotif/SAX/blob/master/src/main/java/net/seninp/jmotif/sax/TSProcessor.java)
.
Take for example an array [1,2,3,4,5,6,7] and PAA size = 4.

The following R code (taken from this repo) generates what seems to me the correct output

    x <- array(1:7, dim=c(7))
    l <- length(x)
    PAA_number = 4
    PAA <- array(0, PAA_number)
    for (i in 1:PAA_number) {
      PAA[i] <- mean(x[round((i - 1) * l/PAA_number + 1):round(i * l/PAA_number)])
      print(paste("segment",i,"[",      # a debug output
              round((i - 1) * l/PAA_number + 1),
              ":",round(i * l/PAA_number),"] ->",
              PAA[i]))
    }

Output is:

    [1] "segment 1 [ 1 : 2 ] -> 1.5"
    [1] "segment 2 [ 3 : 4 ] -> 3.5"
    [1] "segment 3 [ 4 : 5 ] -> 4.5"
    [1] "segment 4 [ 6 : 7 ] -> 6.5"

To the contrary, the TSProcessor paa function generates:

[0] = 1.4285714285714286
[1] = 3.1428571428571428
[2] = 4.8571428571428568
[3] = 6.5714285714285712

Can you check?

**Comment by seninp** [comment]
I believe that the TSProcessor behavior is correct, I'll check an update this thread.

**Comment by seninp** [comment]
Here is an illustration of PAA -- note that my code transforms a straight line into a straight line whereas the proposed transforms jumps around a bit...  ![Issue #10 Illustration] (https://raw.githubusercontent.com/jMotif/SAX/master/src/RCode/issues/Issue10.png)
