### ISSUE TITLE
do you have any examples of using shingles in time series classification?

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/SAX#17]
Hi Senin,

Recently, I came across approach (cosine similarity) that tries to use k-shingles to help classify text documents based on similarity in subsequent string patterns? 
My quick search found that you actually have implemented public classes in Java (in SAXProcessor.java that indeed represents timeseries into Shingles using: 
1) TS2Shingles - for single time series
2) manySeriesToShingles - for multiple time series datasets

However, my question to you is have you attempted classifying time series based on k-shingles ? If yes, does it fair well than SAX-VSM? Any other findings from such..pls advice.

Thanks,
KMB

**Comment by seninp** [comment]
Thank you for the interest in the code. There are few Java classes which I use for my own workflow/experimentation/prototyping. I'd like to keep this as it is without releasing to public. Thanks.
