### ISSUE TITLE
Java API implementing test time series string conversion by individual time series(rows) from CSV

### ISSUE THREAD

**Issue by balajikalluri** [jMotif/SAX#18]
@seninp 

Have you got any equivalent implementation (java API) for the function that read test time series (CSV) dataset row-by-row and then converts them into SAX wordbag with each bag corresponding to individual time series? 

I'm looking for the equivalence to the following R-code...
----------------------------------------------------------------------
for (i in c(1:length(data_test[,1]))) {
  print(paste(i))
  series = data_test[i,]
  bag = series_to_wordbag(series, w, p, a, "exact", 0.01)
------------------------------------------------------------------------

Appreciate your quick help !

Thanks,
KMB

**Comment by balajikalluri** [comment]
`# Step 5: classify the test data
#
labels_predicted = rep(-1, length(MFD[["labels_test"]]))
labels_test = MFD[["labels_test"]]
data_test = MFD[["data_test"]]
for (i in c(1:length(data_test[,1]))) {
  print(paste(i))
  series = data_test[i,]
  bag = series_to_wordbag(series, w, p, a, "exact", 0.01)
  cosines = cosine_sim(list("bag"=bag, "tfidf" = tfidf))
  if (!any(is.na(cosines$cosines))) {
    labels_predicted[i] = which(cosines$cosines == max(cosines$cosines))
  }
}`

**Comment by balajikalluri** [comment]
@seninp 

I'm looking for the equivalence of this R-implementation in Java.

`# classify the test data
#
labels_predicted = rep(-1, length(CBF[["labels_test"]]))
labels_test = CBF[["labels_test"]]
data_test = CBF[["data_test"]]
for (i in c(1:length(data_test[,1]))) {
  print(paste(i))
  series = data_test[i,]
  bag = series_to_wordbag(series, w, p, a, "exact", 0.01)
  cosines = cosine_sim(list("bag"=bag, "tfidf" = tfidf))
  if (!any(is.na(cosines$cosines))) {
    labels_predicted[i] = which(cosines$cosines == max(cosines$cosines))
  }
}
`
Taken from your SAX-VSM R-page [https://github.com/jMotif/jmotif-R](url)

**Comment by seninp** [comment]
This functionality is not a part of this library and will not be. SAX lib is concerned with the discretization transform and the hot-sax algorithm. Sax-vsm lib implements the thing you want.
